permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: yzpniceboy
  email: 403284875@qq.com
  link: http://ccyan.me
  weibo: http://weibo.com/yzp778niceboy/home
  github: http://github.com/ccyany

# 站点信息
title: 这个消息不太准
description: 互联网消息－－说说笑笑
url: http://ccyan.me
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://tp2.sinaimg.cn/1794906921/180/1297591883/1
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-72894091-1
  url: ccyan.me

# disqus 设置
disqus:
  shortname: ccyan